resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

#- name: gcs
#  type: docker-image
#  source:
#    repository: frodenas/gcs-resource
    
#- name: azure-blobstore
#  type: docker-image
#  source:
#    repository: pcfabr/azure-blobstore-resource

resources:
- name: ubuntu-image
  type: docker-image
  source: { repository: ubuntu }
  
- name: pipeline-resources
  type: git
  source:
    uri: ((tasks.uri))
    branch: master
    #username: ((tasks.username))
    #password: ((tasks.password))
    #skip_ssl_verification: true

- name: stembuild-release
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: stemcells-windows-server
    product_version: ((os-version)).(.*)
    sort_by: semver

#- name: stembuild-release
#  type: github-release
#  source:
#    owner: cloudfoundry-incubator
#    repository: stembuild
#    tag_filter: ((os-version)).(.*)

- name: govc
  type: github-release
  source:
    owner: vmware
    repository: govmomi
    tag_filter: 0.21.(.*)

- name: lgpo
  type: s3
  source:
    access_key_id: ((s3.access-key-id))
    bucket: ((s3.bucket))
    secret_access_key: ((s3.secret-access-key))
    versioned_file: lgpo/LGPO.zip
    endpoint: ((s3.endpoint))

#- name: lgpo
#  type: gcs
#  source:
#    json_key: ((gcs.json-key))
#    bucket: ((gcs.bucket))
#    versioned_file: lgpo/lgpo.zip

#- name: lgpo
#  type: azure-blobstore
#  source:
#    storage_account_name: ((azure.storage_account_name))
#    storage_account_key: ((azure.storage_account_key))
#    container: ((azure.container))
#    versioned_file: lgpo/lgpo.zip

- name: autounattend
  type: s3
  source:
    access_key_id: ((s3.access-key-id))
    bucket: ((s3.bucket))
    secret_access_key: ((s3.secret-access-key))
    versioned_file: autounattend/autounattend.xml
    endpoint: ((s3.endpoint))

#- name: autounattend
#  type: gcs
#  source:
#    json_key: ((gcs.json-key))
#    bucket: ((gcs.bucket))
#    versioned_file: autounattend/autounattend.zip

#- name: autounattend
#  type: azure-blobstore
#  source:
#    storage_account_name: ((azure.storage_account_name))
#    storage_account_key: ((azure.storage_account_key))
#    container: ((azure.container))
#    versioned_file: autounattend/autounattend.zip

- name: iso
  type: s3
  source:
    access_key_id: ((s3.access-key-id))
    bucket: ((s3.bucket))
    secret_access_key: ((s3.secret-access-key))
    versioned_file: iso/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.ISO
    endpoint: ((s3.endpoint))

#- name: iso
#  type: gcs
#  source:
#    json_key: ((gcs.json-key))
#    bucket: ((gcs.bucket))
#    versioned_file: iso/(.*).iso

#- name: iso
#  type: azure-blobstore
#  source:
#    storage_account_name: ((azure.storage_account_name))
#    storage_account_key: ((azure.storage_account_key))
#    container: ((azure.container))
#    versioned_file: iso/(.*).iso

- name: stemcell-store
  type: s3
  source:
  source:
    access_key_id: ((s3.access-key-id))
    secret_access_key: ((s3.secret-access-key))
    bucket: ((s3.bucket))
    versioned_file: stemcell/bosh-stemcell-2019.(.*)-vsphere-esxi-windows2019-go_agent.tgz
    endpoint: ((s3.endpoint))

#- name: stemcell-store
#  type: gcs
#  source:
#    json_key: ((gcs.json-key))
#    bucket: ((gcs.bucket))
#    regexp: stemcell/bosh-stemcell-(.*)-vsphere.*\.tgz

#- name: stemcell-store
#  type: azure-blobstore
#  source:
#    storage_account_name: ((azure.storage_account_name))
#    storage_account_key: ((azure.storage_account_key))
#    container: ((azure.container))
#    regexp: stemcell/bosh-stemcell-(.*)-vsphere.*\.tgz

vcenter-params: &vcenter-params
  vcenter_ca_certs: ((vcenter-ca-certs))
  vcenter_url: ((vcenter-url))
  vcenter_username: ((vcenter-username))
  vcenter_password: ((vcenter-password))
  vcenter_datacenter: ((vcenter-datacenter))

vm-params: &vm-params
  base_vm_name: ((base-vm-name))
  vm_folder: ((vm-folder))
  vm_datastore: ((vm-datastore))
  vm_host: ((vm-host))
  vm_cpu: ((vm-cpu))
  vm_network: ((vm-network))
  vm_disk_gb: ((vm-disk-gb))
  vm_memory_mb: ((vm-memory-mb))
  vm_guest_os_id: ((vm-guest-os-id))
  vm_net_adapter: ((vm-net-adapter))
  vm_resource_pool: ((vm-resource-pool))
  esxi_version: ((esxi-version))
  firmware_type: ((firmware-type))
  disk_controller_type: ((disk-controller-type))
  iso_datastore: ((iso-datastore))
  iso_folder: ((iso-folder))

os-params: &os-params
  operating_system_name: ((operating-system-name))
  ip_address: ((ip-address))
  language: ((language))
  gateway_address: ((gateway-address))
  dns_address: ((dns-address))
  admin_password: ((admin-password))
  oobe_unattend_uri: ((oobe-unattend-uri))
  vmware_tools_uri: ((vmware-tools-uri))
  windows_update_module_uri: ((windows-update-module-uri))

######################

jobs:
  - name: create-base
    plan:
      - get: ubuntu-image
      - get: pipeline-resources
      - get: govc
        params:
          globs:
            - govc_linux_amd64.gz
      - get: autounattend
      - get: iso
        #trigger: true #start the pipeline whenever there is a new ISO
      - task: create-base
        file: pipeline-resources/tasks/create-base.yml
        image: ubuntu-image
        input_mapping:
          govc: govc
          autounattend: autounattend
          iso: iso
          pipeline-resources: pipeline-resources
        params:
          <<: *vcenter-params
          <<: *vm-params
          <<: *os-params

  - name: update-base
    plan:
      - get: ubuntu-image
      - get: pipeline-resources
      - get: govc
        params:
          globs:
            - govc_linux_amd64.gz
      - get: stembuild-release
        #trigger: true #start the pipeline whenever there is a new stembuild
        params:
          globs:
            - stembuild-linux-*
      - task: update-base
        file: pipeline-resources/tasks/update-base.yml
        image: ubuntu-image
        input_mapping:
          govc: govc
          pipeline-resources: pipeline-resources
        params:
          <<: *vcenter-params
          <<: *os-params

  - name: clone-base
    plan:
      - get: ubuntu-image
      - get: pipeline-resources
        trigger: true
        passed: [create-base]
      - get: govc
        params:
          globs:
            - govc_linux_amd64.gz
      - get: stembuild-release
        params:
          globs:
            - stembuild-linux-*
      - task: create-base
        file: pipeline-resources/tasks/clone-base.yml
        image: ubuntu-image
        input_mapping:
          govc: govc
          stembuild: stembuild-release
          pipeline-resources: pipeline-resources
        params:
          <<: *vcenter-params
          <<: *vm-params
        
  - name: construct
    plan:
      - get: ubuntu-image
      - get: pipeline-resources
        trigger: true
        passed: [clone-base]
      - get: lgpo
      - get: govc
        params:
          globs:
            - govc_linux_amd64.gz
      - get: stembuild-release
        params:
          globs:
            - stembuild-linux-*
      - task: construct
        file: pipeline-resources/tasks/construct.yml
        image: ubuntu-image
        input_mapping:
          stembuild: stembuild-release
          lgpo: lgpo
          govc: govc
          pipeline-resources: pipeline-resources
        params:
          <<: *vcenter-params
          <<: *vm-params
          <<: *os-params

  - name: package
    plan:
      - get: ubuntu-image
      - get: pipeline-resources
        trigger: true
        passed: [construct]
      - get: govc
        params:
          globs:
            - govc_linux_amd64.gz
      - get: stembuild-release
        params:
          globs:
            - stembuild-linux-*
      - task: package
        file: pipeline-resources/tasks/package.yml
        image: ubuntu-image
        input_mapping:
          stembuild: stembuild-release
          govc: govc
          pipeline-resources: pipeline-resources
        params:
          <<: *vcenter-params
          <<: *vm-params
          <<: *os-params
      - put: stemcell-store
        params:
          file: stemcell/*.tgz
