---
platform: linux

inputs:
- name: pipeline-resources
- name: govc
- name: stembuild

params:
  vcenter_url: ((vcenter-url))
  vcenter_username: ((vcenter-username))
  vcenter_password: ((vcenter-password))
  vcenter_datacenter: ((vcenter-datacenter))
  vcenter_ca_certs: ((vcenter-ca-certs))

  vm_folder: ((vm-folder))

outputs:
- name: stemcell
  
run:
  path: pipeline-resources/tasks/package.sh
